# MD041/first-line-heading : First line heading : https://github.com/DavidAnson/markdownlint/blob/v0.39.0/doc/md041.md
"MD041": false

# MD013/line-length : Line length : https://github.com/DavidAnson/markdownlint/blob/v0.39.0/doc/md013.md
MD013:
  line_length: 180
